apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: flask-project
  namespace: argocd
spec:
  description: Flask application project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'