apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::557690584973:user/flask-app
      username: flask-app
      groups:
        - system:masters
