apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flask-app-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flask-app-role-binding
subjects:
- kind: ServiceAccount
  name: flask-app-sa
  namespace: default
roleRef:
  kind: Role
  name: flask-app-role
  apiGroup: rbac.authorization.k8s.io