apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-audit
spec:
  selector:
    matchLabels:
      name: fluentd-audit
  template:
    metadata:
      labels:
        name: fluentd-audit
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.14
        volumeMounts:
        - name: audit-logs
          mountPath: /var/log/audit
      volumes:
      - name: audit-logs
        hostPath:
          path: /var/log/audit