apiVersion: batch/v1
kind: CronJob
metadata:
  name: trivy-scan
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trivy
            image: aquasec/trivy
            args:
            - image
            - --severity
            - HIGH,CRITICAL
            - your-registry/flask-app:latest
          restartPolicy: OnFailure