apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cost-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kubecost
  endpoints:
  - port: http
    interval: 1m